packages:
  - "features/.devcontainer/features/src/*"
  - "features/.devcontainer/features/test/*"
lockfile: false
confirmModulesPurge: false
update:
  ignoreDeps:
    - typescript
    - "@types/node"
overrides:
  "parse-url": "^11.1.0"
allowBuilds:
  esbuild: false
  unrs-resolver: false
