#!/bin/sh
set -e

mkdir -p /usr/local/bin
install -m 0755 rg /usr/local/bin/rg

mkdir -p /usr/local/share/man/man1
install -m 0644 doc/rg.1 /usr/local/share/man/man1/rg.1

mkdir -p /usr/local/share/bash-completion/completions
install -m 0644 complete/rg.bash /usr/local/share/bash-completion/completions/rg

mkdir -p /usr/local/share/zsh/site-functions
install -m 0644 complete/_rg /usr/local/share/zsh/site-functions/_rg

mkdir -p /usr/local/share/fish/vendor_completions.d
install -m 0644 complete/rg.fish /usr/local/share/fish/vendor_completions.d/rg.fish

mkdir -p /usr/local/share/doc/ripgrep
install -m 0644 COPYING LICENSE-MIT UNLICENSE /usr/local/share/doc/ripgrep/
