<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>DevcontainerConfig.Dotnet</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Features/Features.csproj" />
  </ItemGroup>
</Project>
