services:
  devcontainer:
    env_file:
      - container.env
      - path: ../.local/.env
        required: false
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - WORKSPACES:/workspaces
      - ..:/workspaces/features
volumes:
  WORKSPACES:
